export type Locale='en'|'nl';
export const locales:Locale[]=['en','nl'];
export const dict={
 en:{shop:'SHOP',robes:'ROBES',towels:'TOWELS',world:'OUR WORLD',search:'SEARCH',account:'ACCOUNT',bag:'BAG',newCollection:'NEW COLLECTION',discover:'Discover',discoverWorld:'Discover our world',shopNow:'Shop now',slower:'SLOWER MORNINGS.',made:'MADE TO LIVE IN',madeCopy:'100% cotton. Soft terry inside. Velour finish outside. Finished with our signature wave trim.',stories:'FLOA STORIES',stay:'STAY CLOSE.',stayCopy:'New collections, colours and stories.',add:'ADD TO BAG',colour:'Colour',size:'Size',inStock:'In stock',lowStock:'Low stock',soldOut:'Sold out',details:'Details',fit:'Size & Fit',care:'Material & Care',delivery:'Delivery & Returns'},
 nl:{shop:'SHOP',robes:'BADJASSEN',towels:'HANDDOEKEN',world:'ONS VERHAAL',search:'ZOEKEN',account:'ACCOUNT',bag:'TAS',newCollection:'NIEUWE COLLECTIE',discover:'Ontdek',discoverWorld:'Ontdek onze wereld',shopNow:'Shop nu',slower:'LANGZAME OCHTENDEN.',made:'GEMAAKT OM IN TE LEVEN',madeCopy:'100% katoen. Zachte badstof aan de binnenkant. Velours afwerking aan de buitenkant. Afgewerkt met onze kenmerkende golvende bies.',stories:'FLOA VERHALEN',stay:'BLIJF DICHTBIJ.',stayCopy:'Nieuwe collecties, kleuren en verhalen.',add:'TOEVOEGEN AAN TAS',colour:'Kleur',size:'Maat',inStock:'Op voorraad',lowStock:'Lage voorraad',soldOut:'Uitverkocht',details:'Details',fit:'Maat & Pasvorm',care:'Materiaal & Onderhoud',delivery:'Levering & Retouren'}
} as const;
export function localeFrom(v:string):Locale{return v==='nl'?'nl':'en'}
export const routes={en:{home:'/en',robes:'/en/robes',towels:'/en/towels',world:'/en/our-world',journal:'/en/journal'},nl:{home:'/nl',robes:'/nl/badjassen',towels:'/nl/handdoeken',world:'/nl/ons-verhaal',journal:'/nl/journal'}} as const;
export function switchLocale(path:string,to:Locale){const isProduct=/\/robes\/[^/]+$/.test(path)||/\/badjassen\/[^/]+$/.test(path);const slug=path.split('/').filter(Boolean).at(-1);if(isProduct&&slug)return `${to==='en'?'/en/robes/':'/nl/badjassen/'}${slug}`;if(path.includes('towels')||path.includes('handdoeken'))return routes[to].towels;if(path.includes('our-world')||path.includes('ons-verhaal'))return routes[to].world;if(path.includes('journal'))return routes[to].journal;if(path.includes('robes')||path.includes('badjassen'))return routes[to].robes;return routes[to].home}
