import type { Locale } from './i18n';
export type Money={amount:number;currencyCode:'EUR'};
export type Variant={id:string;sku:string;selectedOptions:{name:'Colour'|'Size';value:string}[];price:Money;availableForSale:boolean;quantityAvailable:number;barcode?:string};
export type Product={id:string;handle:string;category:'robes'|'towels';title:Record<Locale,string>;description:Record<Locale,string>;images:string[];options:{name:'Colour'|'Size';values:string[]}[];variants:Variant[];metafields:{material:string;fit:string;care:string}};
const p=(id:string,handle:string,category:'robes'|'towels',en:string,nl:string,img:string,price:number,colors:string[],sizes:string[]):Product=>({id,handle,category,title:{en,nl},description:{en:'Premium cotton textile designed for slow mornings and everyday rituals.',nl:'Premium katoenen textiel ontworpen voor rustige ochtenden en dagelijkse rituelen.'},images:[img,img],options:[{name:'Colour',values:colors},{name:'Size',values:sizes}],variants:colors.flatMap(c=>sizes.map((s,i)=>({id:`gid://shopify/ProductVariant/${id}-${c}-${s}`,sku:`FLOA-${id}-${c.replace(/\W/g,'').slice(0,4).toUpperCase()}-${s.replace(/\W/g,'').toUpperCase()}`,selectedOptions:[{name:'Colour',value:c},{name:'Size',value:s}],price:{amount:price,currencyCode:'EUR'},availableForSale:!(i===2&&c.includes('Navy')),quantityAvailable:i===0?8:i===1?3:0}))),metafields:{material:'100% cotton · terry interior · velour exterior',fit:sizes.includes('One Size')?'Relaxed one-size fit':'Relaxed fit',care:'Machine wash at 30°C. Wash with similar colours.'}});
export const products:Product[]=[
 p('RB-BP','stripe-robe-burgundy-pink','robes','Stripe Robe — Burgundy / Pink','Gestreepte badjas — Bordeaux / Roze','/images/floa/product-stripe-robe-burgundy-pink.jpg',129,['Burgundy / Pink'],['S','M','L']),
 p('RB-NC','stripe-robe-navy-cream','robes','Stripe Robe — Navy / Cream','Gestreepte badjas — Navy / Crème','/images/floa/product-stripe-robe-navy-cream.jpg',129,['Navy / Cream'],['S','M','L']),
 p('RB-MC','stripe-robe-multicolour','robes','Stripe Robe — Multicolour','Gestreepte badjas — Multicolour','/images/floa/product-stripe-robe-multicolour.jpg',139,['Multicolour'],['One Size']),
 p('RB-SP','wave-robe-soft-pink','robes','Wave Robe — Soft Pink','Wave badjas — Zachtroze','/images/floa/product-wave-robe-soft-pink.jpg',129,['Soft Pink'],['One Size']),
 p('RB-BRP','stripe-robe-brown-pink','robes','Stripe Robe — Brown / Pink','Gestreepte badjas — Bruin / Roze','/images/floa/product-stripe-robe-brown-pink.jpg',129,['Brown / Pink'],['S','M','L']),
 p('TW-LT','stripe-towel-lilac-turquoise','towels','Stripe Towel — Lilac / Turquoise','Gestreepte handdoek — Lila / Turquoise','/images/towel-lilac.svg',49,['Lilac / Turquoise'],['One Size']),
 p('TW-NC','stripe-towel-navy-cream','towels','Stripe Towel — Navy / Cream','Gestreepte handdoek — Navy / Crème','/images/towel-navy.svg',49,['Navy / Cream'],['One Size'])
];
export const getProduct=(handle:string)=>products.find(p=>p.handle===handle);
